ckanext/laissezpasser/views.py
from flask import Blueprint
from flask.views import MethodView
from ckan.common import _, g
from ckan.lib.base import render, abort, request
from ckan.logic import get_action, ValidationError, NotFound, NotAuthorized
import datetime
import ckan.authz as authz
import ckan.logic as logic
import ckan.model as model
import ckan.plugins.toolkit as toolkit
import ckan.lib.helpers as h
import ckan.lib.navl.dictization_functions as dict_fns


laissezpasser = Blueprint("laissezpasser", __name__)


class LaissezPasserEditView(MethodView):
    def post(self, id):
        context = {"model": model, "user": g.user}

        try:
            form_dict = logic.clean_dict(
                dict_fns.unflatten(logic.tuplize_dict(logic.parse_params(request.form)))
            )

            user = get_action("user_show")(context, {"id": form_dict["username"]})

            data_dict = {
                "package_id": id,
                "user_id": user["id"],
                "expires_in": form_dict.get("expires_in"),
            }

            get_action("laissezpasser_create")(context, data_dict)

        except dict_fns.DataError:
            return abort(400, _("Integrity Error"))
        except NotAuthorized:
            message = _("Unauthorized to create pass {}").format(id)
            return abort(401, _(message))
        except NotFound as e:
            h.flash_error(_("User not found"))
            return h.redirect_to("laissezpasser.new_laissezpasser", id=id)
        except ValidationError as e:
            h.flash_error(e.error_summary)
            return h.redirect_to("laissezpasser.new_laissezpasser", id=id)
        else:
            h.flash_success(_("User pass to dataset"))

        return h.redirect_to("laissezpasser.passes_read", id=id)

    def get(self, id):
        context = {"model": model, "user": g.user}
        data_dict = {"id": id}

        try:
            toolkit.check_access("laissezpasser_create", context, data_dict)
            # needed to ckan_extend package/edit_base.html
            pkg_dict = get_action("package_show")(context, data_dict)
        except NotAuthorized:
            message = "Unauthorized to create access passses {}".format(id)
            return abort(401, _(message))
        except NotFound:
            return abort(404, _("Resource not found"))

        user = request.args.get("user_id")
        user_capacity = "member"

        if user:
            user = get_action("user_show")(context, {"id": user})

        extra_vars = {
            "user": user,
            "pkg_dict": pkg_dict,
        }

        return render("ckanext_laissezpasser/package_passes_new.html", extra_vars)


def pass_index(target_user):
    if g.userobj is None:
        return h.redirect_to("user.login")

    site_user = logic.get_action("get_site_user")({"ignore_auth": True}, {})["name"]
    ctx = {"ignore_auth": True, "user": site_user}
    # Only admins can view another user's cart
    username = g.userobj.name

    if g.userobj.name != target_user:
        if g.userobj.sysadmin is True:
            username = target_user
        else:
            return toolkit.redirect_to(f"/passes/{username}")

    try:
        user_dict = logic.get_action("user_show")(
            ctx,
            {
                "include_num_followers": True,
                "include_plugin_extras": True,
                "id": username,
            },
        )
    except logic.NotFound:
        return toolkit.redirect_to(f"/passes/{g.userobj.name}")

    return render(
        "ckanext_laissezpasser/passes.html", extra_vars={"user_dict": user_dict}
    )


def passes_read(id):
    return h.redirect_to("laissezpasser.new_laissezpasser", id=id)


def passes_expire(id, user_id):
    context = {"model": model, "user": g.user}

    try:
        form_dict = logic.clean_dict(
            dict_fns.unflatten(logic.tuplize_dict(logic.parse_params(request.form)))
        )

        # This should set the pass to now explicitly expiring
        now = datetime.datetime.utcnow()

        data_dict = {
            "package_id": id,
            "user_id": user_id,
            "valid_until": now,
        }

        # this will overwrite the existing pass for the user
        get_action("laissezpasser_create")(context, data_dict)

    except dict_fns.DataError:
        return abort(400, _("Integrity Error"))
    except NotAuthorized:
        message = _("Unauthorized to create pass {}").format(id)
        return abort(401, _(message))
    except NotFound as e:
        h.flash_error(_("User not found"))
        return h.redirect_to("laissezpasser.new_laissezpasser", id=id)
    except ValidationError as e:
        h.flash_error(e.error_summary)
        return h.redirect_to("laissezpasser.new_laissezpasser", id=id)
    else:
        h.flash_success(_("Pass expired"))

    return h.redirect_to("laissezpasser.passes_read", id=id)


def passes_delete(id, user_id):
    context = {"model": model, "user": g.user}

    try:
        form_dict = logic.clean_dict(
            dict_fns.unflatten(logic.tuplize_dict(logic.parse_params(request.form)))
        )

        data_dict = {
            "package_id": id,
            "user_id": user_id,
        }

        get_action("laissezpasser_remove")(context, data_dict)

    except dict_fns.DataError:
        return abort(400, _("Integrity Error"))
    except NotAuthorized:
        message = _("Unauthorized to delete pass {}").format(id)
        return abort(401, _(message))
    except NotFound as e:
        h.flash_error(_("User not found"))
    except ValidationError as e:
        h.flash_error(e.error_summary)
    else:
        h.flash_success(_("Pass deleted"))

    return h.redirect_to("laissezpasser.passes_read", id=id)


laissezpasser.add_url_rule("/passes/<target_user>", view_func=pass_index)

laissezpasser.add_url_rule(
    rule="/<id>/passes",
    view_func=passes_read,
    methods=[
        "GET",
    ],
)

laissezpasser.add_url_rule(
    rule="/<id>/passes/new",
    view_func=LaissezPasserEditView.as_view(str("new_laissezpasser")),
    methods=[
        "GET",
        "POST",
    ],
)

laissezpasser.add_url_rule(
    rule="/<id>/passes/delete/<user_id>",
    view_func=passes_delete,
    methods=[
        "POST",
    ],
)

laissezpasser.add_url_rule(
    rule="/<id>/passes/expire/<user_id>",
    view_func=passes_expire,
    methods=[
        "POST",
    ],
)


def get_blueprints():
    return [laissezpasser]

ckanext/laissezpasser/templates/ckanext_laissezpasser/package_passes.html
{% extends "package/edit_base.html" %}

{% block subtitle %}{{ _('Collaborators') }} {{ g.template_title_delimiter }} {{ super() }}{% endblock %}

{% block page_primary_action %}
  {% if h.check_access('package_collaborator_create', {'id': pkg_dict.id})%}
    {% link_for _('Add Collaborators'), named_route='laissezpasser.new_laissezpasser', id=pkg_dict.name, class_='btn btn-primary', icon='plus-square' %}
  {% endif %}
{% endblock %}

{% block primary_content_inner %}
  {% set collaborators = h.get_collaborators(pkg_dict['id'])%}
  {% set count = collaborators|length %}
  {% set collaborators_count = ungettext('{count} collaborator', '{count} collaborators', count).format(count=count) %}
  <h3 class="page-heading">{{ collaborators_count }}</h3>
  <table class="table table-header table-hover table-bordered">
    <thead>
      <tr>
          <th>{{ _('User') }}</th>
          <th>{{ _('Role') }}</th>
          <th></th>
      </tr>
    </thead>
    <tbody>
      {% for user_id, capacity in collaborators %}
        <tr>
          <td class="media">
            {{ h.linked_user(user_id, maxlength=20) }}
          </td>
          <td>{{ capacity }}</td>
          <td>
            <div class="btn-group pull-right">
                <a class="btn btn-default btn-sm" href="{{ h.url_for('laissezpasser.new_laissezpasser', id=pkg_dict.name, user_id=user_id) }}" title="{{ _('Edit') }}">
                <i class="fa fa-wrench"></i>
              </a>
              <a class="btn btn-danger btn-sm" href="{{ h.url_for('laissezpasser.passes_delete', id=pkg_dict.name, user_id=user_id) }}" data-module="confirm-action" data-module-content="{{ _('Are you sure you want to delete the pass for this user?') }}" title="{{ _('Delete') }}">{% block delete_button_text %}<i class="fa fa-times"></i>{% endblock %}</a>
            </div>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

ckanext/laissezpasser/templates/ckanext_laissezpasser/package_passes_new.html
{% extends "package/edit_base.html" %}

{% import 'macros/form.html' as form %}

{% block subtitle %}{{ _('Edit Pass') if user else _('Add Pass') }} - {{ super() }}{% endblock %}

{% block primary_content_inner %}
  {% link_for _('Back to Manage'), named_route=pkg.type ~ '.edit', id=pkg.name, class_='btn btn-default pull-right', icon='arrow-left' %}
  <h1 class="page-heading">
    {% block page_heading %}{{ _('Edit Pass') if user else _('Add Pass') }}{% endblock %}
  </h1>

  {% set url = h.url_for('laissezpasser.new_laissezpasser', id=pkg.name) %}

  {% snippet 'ckanext_laissezpasser/snippets/list_passes.html', passes=h.issued_passes(pkg.name, filter_valid=False), url=url %}

  {% block form %}
  {{ h.csrf_input() if 'csrf_input' in h }}
  <form class="dataset-form add-member-form" method='post'>
    <div class="row">
      <div class="col-md-5">
        <div class="form-group control-medium">
          {% if not user %}
            <label class="control-label" for="username">
              {{ _('Existing User') }}
            </label>
            <p>
              {{ _('If you wish to add a pass for an existing user, search for their username below.') }}
            </p>
          {% endif %}
          <div class="controls">
            {% if user %}
              <input type="hidden" name="username" value="{{ user.name }}" />
              <input id="username" name="username" type="text" value="{{ user.name }}"
              disabled="True" class="form-control">
            {% else %}
                <input id="username" type="text" name="username" placeholder="{{ _('Username') }}"
              value="" class="control-medium" data-module="autocomplete"
              data-module-source="/api/2/util/user/autocomplete?q=?">
            {% endif %}
          </div>
        </div>
      </div>
    </div>

    {% set format_attrs = {'data-module': 'autocomplete'} %}


  <div class="form-group ">
    {{ form.input('expires_in', label=_('Duration of pass in days'), is_required=true, type='number', value=h.pass_duration()) }}
  </div>

    <div class="form-actions">
      {% if user %}
        <a href="{{ h.url_for('laissezpasser.passes_delete', id=pkg_dict.id, user_id=user.name) }}" class="btn btn-danger pull-left" data-module="confirm-action" data-module-content="{{ _('Are you sure you want to delete the pass for this user?') }}">{{ _('Delete') }}</a>
        <button class="btn btn-primary" type="submit" name="submit" >
          {{ _('Delete Pass') }}
        </button>
      {% else %}
        <button class="btn btn-primary" type="submit" name="submit" >
          {{ _('Add Pass') }}
        </button>
      {% endif %}
    </div>
  </form>
  {% endblock %}
{% endblock %}

{% block secondary_content %}
{{ super() }}
<div class="module module-narrow module-shallow">
  <h2 class="module-heading">
    <i class="fa fa-lg fa-info-circle"></i>
    {{ _('What is a pass and how long for?') }}
  </h2>
  <div class="module-content">
    {% trans %}
      <p>
      A Dataset Access Pass provides temporary access to a dataset, it's metadata and attached resources for a user.
      </p>
      <p>
      A Dataset Access Pass is for a single dataset and is only valid for a limited time.   Valid passes
      for this dataset are displayed to the right.  A toggle is provided to also show expired passes if
      that information is required.
      </p>
      <p>
      When the user views the dataset, the time of expiry will be shown.
      </p>
      <p>
      To add a pass, you will need to know the CKAN username for the user.
      It is recommended to go with the default duration in days for the pass to be added.
      </p>
    {% endtrans %}
  </div>
{% endblock %}

ckanext/laissezpasser/templates/ckanext_laissezpasser/passes.html
{% extends "user/read.html" %}

{% block page_primary_action %}
  <h2>{{ _('Dataset Access Passes') }}</h2>
{% endblock %}

{% block primary_content_inner %}
  <h2 class="hide-heading">
    {% block page_heading %}{{ _('Datasets') }}{% endblock %}
  </h2>
  {% block package_list %}
  {% if h.has_passes(user.name) %}
    {# render differently if a sysadmin #}
    {% if h.check_access('sysadmin') %}
      <p>This summary of passes held by user (showing valid and expired) is only available to system administrators</p>
      {% set url = h.url_for('laissezpasser.pass_index', target_user=user.name) %}
      {% snippet 'ckanext_laissezpasser/snippets/list_passes.html', passes=h.held_passes(user.name, filter_valid=False), url=url, key='dataset' %}
    {% else %}
      <p>
      A Dataset Access Pass provides you temporary access to a dataset, it's metadata and attached resources.  
      </p>
      <p>
      A Dataset Access Pass is only valid for a limited time and only valid passes are displayed below.  When
      you view the dataset, the time of expiry will be shown.   If none are listed below, all previous 
      passes have now expired.
      </p>
      {% snippet 'snippets/package_list.html', packages=h.package_passes(user.name, filter_valid=True) %}
    {% endif %}
  {% else %}
    {% if is_myself %}
      <p>
      A Dataset Access Pass provides you temporary access to a dataset, it's metadata and attached resources.  
      </p>
      <p class="empty">
        {{ _('You do not have any passes to access datasets.') }}
      </p>
    {% else %}
      <p class="empty">
        {{ _('User does not have any passes to access datasets.') }}
      </p>
    {% endif %}
  {% endif %}
  {% endblock %}
{% endblock %}